language: java
jdk: openjdk8
sudo: false

services:
  - docker

env:
  global:
    - secure: "VuKZtLUhIqLm3k9o7YzsT/y3wAkieZpH4MxqfFsT/N4uRnrWJGHnGiCyHOkGEjzf8By8DapM/z+emo0YbJGDnRu84jI5JueQ6RK5SyItKFl00xc17FK9Tt6Bv6DHoWHwb6yP2KRhXdIYzn+b1AGq5fj+3PawTjJ4dSe7cJ+sIuW3IVeVTwlMRmGcoUJBeSH/YzMLnnCiK73cdyzCwuu8ggB6In2tamMK/UYS4Arm42gpa2rOOAqn8kO3s1w4j7n0BIXqPOp7bPr+yltoAm+8yBFsHAuOWtwfyIfcTxkvdj7fwLri2pCxBNWNSKT6bF4YqWYt5vtUhdNk1OuvL3qHeg+QlfZo6oILwaiTMTgJ4+r0XIFYOZU0zFUqs8W9FrB+2R5gr2ZlhQkH9tSF1raxoKKiNohPEKPv5BEvjs0JfszMNyIHUAZYCcfU5G9qNCblszaHGtUW8gqdGWU8WpraJg9nLvzF5LrD5E8xjceTfnjaquC9rs4g0/E0LOH3POkiGI/x7mh8UnaE0DY3G8RnFZyXv/F27JnOgU0YXuoBOxbkikLD2kxtyID0xkney2sHndCNu6rr/TOd8WFxK/XEEXRbpGp6jY7uLGu/73VvHhyoLXrYG7dPw9921r8PtrnEMr8bJ/gI3uhBTgMu0j5d4qKmausQNlA3+JHSYrISxKE="
    - secure: "o+J0QUwMPqcJ2s2dQPfONjfsqW8XjL1DOEORBsZpnJXq/Wmj3zkiq1hbxAwkhDe04lSOgI33sp7pSHr4cAvhkMVxwCcSgCIEbq/d94G/VTVd8QfxFUhv21ne4UHngFKaABzhUEEHER0Qz8BGzVMx2AXlphQVvb2jm1p/gDuiBwEilBf85sKEjNa1/TM27NJEaKzqZ468DOrgOuKvYIEsJwxF1zdDiv4R35FHsfgHpaMGfpsHg9zHjwrAg8SaRqzzJoXzIkQPxM/1efU3jGq4VfQzu32EwnxwAb/khX7eOpBG7LsdOHIzt0nI+o859L9ZGr7wwtpg/jS+WOqt0xdJ43n+vFHkhae/Yi4RozTVXjQ5lwnC6n3ObKlqZRmFSMIqxbQUFwPxFgpyKZ9f+Nr/0N/xz6Z7XUovV94hoK47s0LxM1oIq8B4v2+pZ73GgGG53acwL6xA6GNKVjlCqxeOoqjaT1c5+g5ZSn4ovbuULmFD5bUvT8H9M9EdGM350gRrIhOXnhPmM8euv6YLya0SVoc7vIQepT+zAaYjILgJNJIifWdKd8nJiVzwqkAIOxiRxXNXWEqZt5Vzz36uNURBviiTf3aBwUhZNYIf/RJ1JOxuJPbYSbr9oP5qlpSUQ74Z1F7NnJBhj375Lb9AaCphkZr9iRHVkUSANMlQLJnm3aY="
    - secure: "TsvUjcbr10CBdi6ktYzAvrcNRtYfsyV8lPp+y+vu5sX/pKd6vqyR8mPktIx19OCbQFiXpSLXZMXvEzcarJm2T9499WsYRbaml9t1zrTpy+I/Y6UdoYfwD6e7kuSaZXnJiA8x5R2JZueFKHpeQ7cWTT9J+eDto/jA66+jS2ZH30cPEVFdMGrqKClhXJEwkH8y1tOLUyznT24ea3FKta+wKd6/iRn1jU8KgcU9E23WK1xy9f2A/22z7pUSAPzer8Fskp9zHPRWbXphBgCXNCU2wyonCjw/VxOP3L/2kW9rMYMWNSUGto8xaSSrveuaL834VR93DPhxEPiLj0LlkhrcBXt3YR6bb0QbUTPrT/5KFLLgQg+M/2+8EymTlWy/A/vmr2yraZ8rPSD+xq0hvkr76fHGF9m+232guuK79dIbh7Qp+98/zzge5tR4fcnTQKlDU0zWx64aFG1HLnlnfqB5PSZcp8j/ptrrnTYUqKbhAeCdN0epIKaATgypqzypqObg1j13Vess4l/oYRZ1/mk9KgbFAsBUHj9OfozEXG1zZgKm30ldTO79DicLKdp2Bw2bUCx3g80is6wf4gH5ySpUN2S9HRnplEa0YCtIlji9RVNMYiP0Z+kvC154bqQULGMCipT8RkvqZG+E71wj1RBkDL6EAz61SZ6JWAjUDY3Vn/U="
    - secure: "SSQwt1acl5Z/7UjNsV4KPNgZDrO/W0ofWv9jpKNIVyzC1Lush3zp9EMVQb1vnB4y6LqkYwWkhFi7tmlayk+I4c6N3ZgVi/hXSI28PIWsOJO11VxnBsyr+xvCE0bTOD5t2DIBDplLdFTh/cWaAyS2A+5YTPZeIObhoIan3e0teMIKyUKh+CFgY9KFqdx11cLb2jOTKauE1ijV81ITNGPLpS4CZPOWItJWDdVwvYIQVSJe4odNxKLUx/rl57yitXmz7IAPfJJhPUPbC+WDObVN6S90a8Ohq1jPp0hccUr8V3ElptiL1K1j7Paf153L9Ca2KWls/AeyC4pcYsdJ7qsZEUGZTxapuT5TMSvzZsGE0uBLhAIgJD2jfqgoLebNDGY0eNpOSxJWrw5zxQiyM7dQJ8+1V9k6IAGGdz9PXt3pCMVi6zvm6VN1w1wKHHv8S6gfqIORuZwX0vJ8DaT4a8XEjCzPXWnB2hPyVgeZU608MziJzlnrXnVn2bN5rreCNIWqUV+car21knBN+6KylC7jZOZjcnY490pEsaYO2KzMWt5XqJtet25+MVEn+Ta0R9hm6pFxcL492L/czDqht4beW9UmhbcLyUkWhwhNtyhbQxuiDhcqIxAyfAEVpRms0XpWonjP1F8jSmMNtfnttNOHBEt7jKEwEv9n13ZbWTbnFiM="
    - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "sivaprasadreddy-github"
    token:
      secure: $SONAR_TOKEN

script:
  - export SPRING_BOOT_APP_NAME=bookarker-kotlin
  - cd $SPRING_BOOT_APP_NAME
  - ./mvnw clean verify
  - cd ..

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - export SPRING_BOOT_APP_NAME=bookarker-kotlin
  - cd $SPRING_BOOT_APP_NAME
  - ../scripts/travis-publish-docker.sh
  - ../scripts/deploy-on-heroku.sh
  - cd ..
