export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const RECEIVE_BOOKMARKS = "RECEIVE_BOOKMARKS";
export const RECEIVE_SELECTED_TAG = "RECEIVE_SELECTED_TAG";
export const RECEIVE_ALL_TAGS = "RECEIVE_ALL_TAGS";
export const RECEIVE_SEARCH_BOOKMARKS = "RECEIVE_SEARCH_BOOKMARKS";
export const CREATE_BOOKMARK_SUCCESS = "CREATE_BOOKMARK_SUCCESS";
