version: '3.1'
services:

  bookmarker:
    build: .
    container_name: bookmarker
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://bm-postgresdb:5432/appdb
      SPRING_DATASOURCE_USERNAME: siva
      SPRING_DATASOURCE_PASSWORD: secret
      APPLICATION_LOGSTASH_HOST: logstash
    depends_on:
      - bm-postgresdb

  bm-postgresdb:
    image: postgres:10.7
    container_name: bm-postgresdb
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
