name: Bookmarker Master CI

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B clean install
      - name: SonarCloud Scan
        run: mvn -B sonar:sonar -Pci -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./bookmarker-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Publish To Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Package with Maven
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        working-directory: ./bookmarker-java
      - name: Publish Docker image
        run: docker push $REPO
        working-directory: ./bookmarker-java

  heroku:
    name: Deploy To Heroku
    runs-on: ubuntu-18.04
    needs: [test, docker]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Package with Maven
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Deploy To Heroku
        run: mvn heroku:deploy -P ci
        working-directory: ./bookmarker-java
